// Generated by delombok at Tue Apr 18 17:58:31 CST 2023
package cn.edu.sustech.cs110.snake.model;

import cn.edu.sustech.cs110.snake.enums.Direction;
import java.util.ArrayList;
import java.util.List;

public class Snake {
    private final List<Position> body = new ArrayList<>(15 * 15 / 2);
    private Direction direction;

    @java.lang.SuppressWarnings("all")
    public List<Position> getBody() {
        return this.body;
    }

    @java.lang.SuppressWarnings("all")
    public Direction getDirection() {
        return this.direction;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Snake(body=" + this.getBody() + ", direction=" + this.getDirection() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Snake(final Direction direction) {
        this.direction = direction;
    }

    @java.lang.SuppressWarnings("all")
    public void setDirection(final Direction direction) {
        if (this.direction != null && this.direction.isOpposite(direction)) {
            return;
        }
        this.direction = direction;
    }
}
